In [17]:
import numpy as np

In [18]:
#seed es para poner el canal 1 asi estoy vinculando a un orden específico
np.random.seed(1)

np.random.randint(1,21, size = 15)


array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [19]:
#L.sort ordena de manera ascendente, de la lista random sacamos solo los pares
L=[i for i in np.random.randint(1,21, size=40) if i%2 ==0]
L.sort ()
L

[2,
 4,
 4,
 6,
 8,
 8,
 10,
 10,
 10,
 10,
 12,
 12,
 14,
 14,
 14,
 16,
 16,
 18,
 18,
 18,
 18,
 20,
 20]

In [20]:
# muestra el número más alto
L.pop(4)

#L.pop(algun numero impar) se salta un numero en el conteo
#L.pop(algun numero par) no se salta numero en el conteo

8

In [22]:
#quita un número especificado
L.remove(4)
L

[2, 6, 8, 10, 10, 10, 10, 12, 12, 14, 14, 14, 16, 16, 18, 18, 18, 18, 20, 20]

In [10]:
# agrega el numero
L+[4]

[2,
 4,
 6,
 8,
 8,
 10,
 10,
 10,
 10,
 12,
 12,
 14,
 14,
 14,
 16,
 16,
 18,
 18,
 18,
 18,
 20,
 4]

In [23]:
#convertir L en un vector
L_arreglo=np.array(L)
L_arreglo


array([ 2,  6,  8, 10, 10, 10, 10, 12, 12, 14, 14, 14, 16, 16, 18, 18, 18,
       18, 20, 20])

In [24]:
#determinamos el largo del vector, si el vector es primo no se puede crear (1*primo)
len(L_arreglo)

20

In [25]:
#creamos la matriz
L_arreglo.reshape(10,2)


array([[ 2,  6],
       [ 8, 10],
       [10, 10],
       [10, 12],
       [12, 14],
       [14, 14],
       [16, 16],
       [18, 18],
       [18, 18],
       [20, 20]])

In [27]:
#forma la matriz
L_arreglo.reshape(5,4)

array([[ 2,  6,  8, 10],
       [10, 10, 10, 12],
       [12, 14, 14, 14],
       [16, 16, 18, 18],
       [18, 18, 20, 20]])

In [59]:
#crea la matriz
M=np.array([2,3,14,19,13,0,5,25,69])
M

array([ 2,  3, 14, 19, 13,  0,  5, 25, 69])

In [53]:
L_matriz = np.array([3,4,5,1,2,3,7,8,9]). reshape(3,3)
L_matriz

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [51]:
M_matriz = np.array([2,3,14,19,13,0,25,6,9]). reshape(3,3)
M_matriz

array([[ 2,  3, 14],
       [19, 13,  0],
       [25,  6,  9]])

In [54]:
# multiplicar vectores
# vector es matriz de n*1
# arreglo es matriz
N = L_matriz @ M_matriz
N

array([[207,  91,  87],
       [115,  47,  41],
       [391, 179, 179]])

In [55]:
#encontrar determinante
np.linalg.det(N)

0.0